### ISSUE TITLE
Evaluate if solver_specific makes solve! type unstable

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/SolverCore.jl#30]
> We should evaluate whether `solver_specific` makes `solve!()` type unstable or not.

_Originally posted by @dpo in https://github.com/JuliaSmoothOptimizers/SolverCore.jl/issues/26#issuecomment-1194636807_

**Comment by dpo** [comment]
Maybe design a type for solver-specific data, as suggested by @geoffroyleconte in #31.
