### ISSUE TITLE
Move `dummy_solver` to `src`

### ISSUE THREAD

**Issue by tmigot** [JuliaSmoothOptimizers/SolverCore.jl#36]
The `dummy_solver` is used in a number of packages, so it would be great to have in one place and if so I think SolverCore.jl is the right one because it is the less demanding in term of depencies.

For instance, the following PR
https://github.com/JuliaSmoothOptimizers/SolverCore.jl/pull/34#pullrequestreview-1072582042
would have to be done in SolverBenchmark.jl and SolverTest.jl (others?) now...

https://github.com/JuliaSmoothOptimizers/SolverCore.jl/pull/26 @dpo @geoffroyleconte

**Comment by dpo** [comment]
Or maybe SolverTest?

**Comment by tmigot** [comment]
SolverTest depends on SolverCore, so we would not be able to use it here I think

**Comment by tmigot** [comment]
SolverTest uses SolverCore for `dummy_solver`
