### ISSUE TITLE
Documentation of GenericExecutionStats seems outdated

### ISSUE THREAD

**Issue by pjssilva** [JuliaSmoothOptimizers/SolverCore.jl#52]
The documention of [`GenericExecutionStats`](https://juliasmoothoptimizers.github.io/SolverCore.jl/stable/reference/#SolverCore.GenericExecutionStats) seems to imply that the first (positional) parameter is the `status`. But looking at the code the status is now a keyword parameter. It looks like there is only a single positional parameter now which is `nlp`.

**Comment by tmigot** [comment]
That's true thanks. It has actually been fixed here https://github.com/JuliaSmoothOptimizers/SolverCore.jl/commit/3ca76ba75c37e87ae42c89ab88d2a13361c7bd5c , but there was no new release since.
